default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test

production:
  <<: *default
  database: demo_production
